parse:
  additional_commands:
    cpmfindpackage:
      pargs:
        nargs: "*"
        flags: []
      spelling: CPMFindPackage
      kwargs:
        NAME: "*"
        EXECUTABLE: "*"
        DEPENDENCIES: "*"
    setup_target_for_coverage_gcovr:
      kwargs:
        NAME: "*"
        EXECUTABLE: "*"
        DEPENDENCIES: "*"
    setup_target_for_coverage_gcovr_html:
      kwargs:
        NAME: "*"
        EXECUTABLE: "*"
        DEPENDENCIES: "*"
format:
  dangle_parens: true
  line_ending: unix
  line_width: 240
  max_pargs_hwrap: 8
  min_prefix_chars: 8
  tab_size: 4
markup:
  enable_markup: false
  bullet_char: "*"
  enum_char: .
