name: auto-clang-format

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clang Format
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: "."
          exclude: "./third_party ./external"
          extensions: "h,cpp,hpp"
          clangFormatVersion: 12
          inplace: True

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: ":art: Committing clang-format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
