name: Documentation

on:
  push:
    branches: [main, master, dev]
    paths: [include/**, lib/**, src/**]
  pull_request:
    branches: [main, master, dev]
    paths: [include/**, lib/**, src/**]

concurrency:
  group: documentation
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: "${{ github.workspace }}/external/vcpkg"
          vcpkgJsonGlob: "${{ github.workspace }}/vcpkg.json"

      - name: Install Packages
        run: sudo apt-get install doxygen graphviz

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-multi-vcpkg"
          configurePresetAdditionalArgs: '[`-DENABLE_DOXYGEN=ON`]'
          buildPreset: "ninja-multi-vcpkg-release"
          buildPresetAdditionalArgs: '[`--target doxygen`, ` -j4`]'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  #: https://github.com/peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/docs/html
