name: Documentation

on:
  push:
    branches: [main, master, dev]
    tags:
      - "*"
  workflow_dispatch:

concurrency:
  group: documentation
  cancel-in-progress: true

env:
  BUILD_TYPE: Debug

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - name: Install Packages

        run: |
          sudo apt-get install doxygen graphviz
          pip install jinja2 Pygments

      - name: Configure
        run: cmake -H. -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_DOXYGEN=On

      - name: Generate Doxygen Documentation
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target doxygen -j4

      - name: Cache Build Directory
        uses: actions/cache@v3
        with:
          path: build
          key: cmake-build-documentation-${{ hashFiles('CMakeCache.txt') }}

      #: https://github.com/peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/docs/html
